# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./movie_booking.db
    volumes:
      - ./data:/app/data

  # For production, you can add PostgreSQL and Redis
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: movie_booking
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password